name: Python unittest

on:
  pull_request:
    paths:['python/**/*.py']

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - run: python -m unittest python/*.py