name: Share

on: push

jobs:
  share:
    runs-on: ubuntu-latest
    steps:
      # ステップIDを設定
      - id: parent
        # GITHUB_OUTPUTへ書き出し
        run: echo "result=Hello" >> "${GITHUB_OUTPUT}"
      # stepsコンテキストから参照
      - env:
          RESULT: ${{ steps.parent.outputs.result }}
        run: echo "${RESULT}"
